import bina1_1 from "../images/binebi/1.jpg";
import bina1_2 from "../images/binebi/1_1.jpg";
import bina2_1 from "../images/binebi/2.jpg";
import bina2_2 from "../images/binebi/2_1.jpg";
import bina3_1 from "../images/binebi/3.jpg";
import bina3_2 from "../images/binebi/3_1.jpg";
import bina4_1 from "../images/binebi/4.jpg";
import bina4_2 from "../images/binebi/4_1.jpg";
import bina5_1 from "../images/binebi/5.jpg";
import bina5_2 from "../images/binebi/5_1.jpg";
import bina6_1 from "../images/binebi/6.jpg";
import bina6_2 from "../images/binebi/6_1.jpg";
import bina7_1 from "../images/binebi/7.jpg";
import bina7_2 from "../images/binebi/7_1.jpg";
import bina8_1 from "../images/binebi/8.jpg";
import bina8_2 from "../images/binebi/8_1.jpg";
import bina9_1 from "../images/binebi/9.jpg";
import bina9_2 from "../images/binebi/9_1.jpg";
import bina10_1 from "../images/binebi/10.jpg";
import bina10_2 from "../images/binebi/10_1.jpg";
import bina11_1 from "../images/binebi/11.jpg";
import bina11_2 from "../images/binebi/11_1.jpg";
import bina12_1 from "../images/binebi/12.jpg";
import bina12_2 from "../images/binebi/12_1.jpg";
import bina13_1 from "../images/binebi/13.jpg";
import bina13_2 from "../images/binebi/13_1.jpg";
import bina14_1 from "../images/binebi/14.jpg";
import bina14_2 from "../images/binebi/14_1.jpg";
import bina15_1 from "../images/binebi/15.jpg";
import bina15_2 from "../images/binebi/15_1.jpg";
import bina16_1 from "../images/binebi/16.jpg";
import bina16_2 from "../images/binebi/16_1.jpg";


const MazaService = {
     binebi: [
        {
          project: 1,
          name: "ტიპიური პროექტი 1",
          floors: [
            "I",
            "II",
            "III",
            "IV",
            "V",
            "VI",
            "VII",
            "VIII",
            "IX",
            "X",
            "XI",
          ],
          sold: [
            false,
            true,
            false,
            false,
            false,
            false,
            true,
            false,
            false,
            false,
            false,
          ],
          livingArea: 27.67,
          summerArea: 3.7,
          fullArea: 31.37,
          entrance: 3.28,
          bathroom: 3.6,
          bedroom1: 20.79,
          bedroom2: null,
          livingRoom: null,
          images: [bina1_1, bina1_2]
        },
        {
          project: 2,
          name: "ტიპიური პროექტი 2",
          floors: [
            "I",
            "II",
            "III",
            "IV",
            "V",
            "VI",
            "VII",
            "VIII",
            "IX",
            "X",
            "XI",
          ],
          sold: [
            true,
            true,
            true,
            true,
            true,
            true,
            true,
            false,
            false,
            true,
            false,
          ],
          livingArea: 54.37,
          summerArea: 9.40,
          fullArea: 63.77,
          entrance: 4.56,
          bathroom: 3.21,
          bedroom1: 12.07,
          bedroom2: 12.1,
          livingRoom: 20.89,
          images: [bina2_1, bina2_2]
        },
        {
          project: 3,
          name: "ტიპიური პროექტი 3",
          floors: [
            "I",
            "II",
            "III",
            "IV",
            "V",
            "VI",
            "VII",
            "VIII",
            "IX",
            "X",
            "XI",
          ],
          sold: [
            false,
            false,
            true,
            true,
            true,
            false,
            false,
            false,
            false,
            false,
            false,
          ],
          livingArea: 42.85,
          summerArea: 8.17,
          fullArea: 51.02,
          entrance: 5.96,
          bathroom: 3.96,
          bedroom1: 14.08,
          bedroom2: null,
          livingRoom: 17.53,
          images: [bina3_1, bina3_2]
        },
        {
          project: 4,
          name: "ტიპიური პროექტი 4",
          floors: [
            "I",
            "II",
            "III",
            "IV",
            "V",
            "VI",
            "VII",
            "VIII",
            "IX",
            "X",
            "XI",
          ],
          sold: [
            false,
            false,
            false,
            false,
            false,
            true,
            true,
            true,
            true,
            true,
            false,
          ],
          livingArea: 43.06,
          summerArea: 8.24,
          fullArea: 51.30,
          entrance: 6.43,
          bathroom: 3.45,
          bedroom1: 14.63,
          bedroom2: null,
          livingRoom: 18.55,
          images: [bina4_1, bina4_2]
        },
        {
          project: 5,
          name: "ტიპიური პროექტი 5",
          floors: [
            "I",
            "II",
            "III",
            "IV",
            "V",
            "VI",
            "VII",
            "VIII",
            "IX",
            "X",
            "XI",
          ],
          sold: [
            true,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            true,
            false,
            true,
          ],
          livingArea: 44.76,
          summerArea: 8.24,
          fullArea: 53.00,
          entrance: 4.2,
          bathroom: 3.66,
          bedroom1: 14.13,
          bedroom2: null,
          livingRoom: 21.41,
          images: [bina5_1, bina5_2]
        },
        {
          project: 6,
          name: "ტიპიური პროექტი 6",
          floors: [
            "I",
            "II",
            "III",
            "IV",
            "V",
            "VI",
            "VII",
            "VIII",
            "IX",
            "X",
            "XI",
          ],
          sold: [
            true,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            true,
          ],
          livingArea: 44.76,
          summerArea: 8.24,
          fullArea: 53.00,
          entrance: 4.2,
          bathroom: 3.61,
          bedroom1: 14.11,
          bedroom2: null,
          livingRoom: 20.80,
          images: [bina6_1, bina6_2]
        },
        {
          project: 7,
          name: "ტიპიური პროექტი 7",
          floors: [
            "I",
            "II",
            "III",
            "IV",
            "V",
            "VI",
            "VII",
            "VIII",
            "IX",
            "X",
            "XI",
          ],
          sold: [
            true,
            false,
            false,
            false,
            true,
            false,
            false,
            false,
            false,
            false,
            true,
          ],
          livingArea: 44.76,
          summerArea: 8.24,
          fullArea: 53.00,
          entrance: 4.73,
          bathroom: 3.61,
          bedroom1: 14.11,
          bedroom2: null,
          livingRoom: 21.02,
          images: [bina7_1, bina7_2]
        },
        {
          project: 8,
          name: "ტიპიური პროექტი 8",
          floors: [
            "I",
            "II",
            "III",
            "IV",
            "V",
            "VI",
            "VII",
            "VIII",
            "IX",
            "X",
            "XI",
          ],
          sold: [
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            true,
          ],
          livingArea: 44.76,
          summerArea: 8.24,
          fullArea: 53.00,
          entrance: 4.73,
          bathroom: 3.74,
          bedroom1: 14.11,
          bedroom2: null,
          livingRoom: 21.06,
          images: [bina8_1, bina8_2]
        },
        {
          project: 9,
          name: "ტიპიური პროექტი 9",
          floors: [
            "I",
            "II",
            "III",
            "IV",
            "V",
            "VI",
            "VII",
            "VIII",
            "IX",
            "X",
            "XI",
          ],
          sold: [
            false,
            false,
            true,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
          ],
          livingArea: 43.06,
          summerArea: 8.24,
          fullArea: 51.30,
          entrance: 6.43,
          bathroom: 3.45,
          bedroom1: 14.72,
          bedroom2: null,
          livingRoom: 16.95,
          images: [bina9_1, bina9_2]
        },
        {
          project: 10,
          name: "ტიპიური პროექტი 10",
          floors: [
            "I",
            "II",
            "III",
            "IV",
            "V",
            "VI",
            "VII",
            "VIII",
            "IX",
            "X",
            "XI",
          ],
          sold: [
            false,
            false,
            true,
            true,
            false,
            false,
            false,
            false,
            false,
            false,
            true,
          ],
          livingArea: 42.85,
          summerArea: 8.17,
          fullArea: 51.02,
          entrance: 6.18,
          bathroom: 3.54,
          bedroom1: 14.08,
          bedroom2: null,
          livingRoom: 17.53,
          images: [bina10_1, bina10_2]
        },
        {
          project: 11,
          name: "ტიპიური პროექტი 11",
          floors: [
            "I",
            "II",
            "III",
            "IV",
            "V",
            "VI",
            "VII",
            "VIII",
            "IX",
            "X",
            "XI",
          ],
          sold: [
            true,
            true,
            true,
            false,
            true,
            false,
            false,
            false,
            false,
            false,
            true,
          ],
          livingArea: 54.37,
          summerArea: 9.40,
          fullArea: 63.77,
          entrance: 4.59,
          bathroom: 3.15,
          bedroom1: 12.07,
          bedroom2: 12.1,
          livingRoom: 20.89,
          images: [bina11_1, bina11_2]
        },
        {
          project: 12,
          name: "ტიპიური პროექტი 12",
          floors: [
            "I",
            "II",
            "III",
            "IV",
            "V",
            "VI",
            "VII",
            "VIII",
            "IX",
            "X",
            "XI",
          ],
          sold: [
            false,
            false,
            true,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            true,
          ],
          livingArea: 27.67,
          summerArea: 3.7,
          fullArea: 31.37,
          entrance: 3.45,
          bathroom: 3.5,
          bedroom1: 27.67,
          bedroom2: null,
          livingRoom: null,
          images: [bina12_1, bina12_2]
        },
        {
          project: 13,
          name: "ტიპიური პროექტი 13",
          floors: [
            "I",
            "II",
            "III",
            "IV",
            "V",
            "VI",
            "VII",
            "VIII",
            "IX",
            "X",
            "XI",
          ],
          sold: [
            true,
            true,
            false,
            false,
            false,
            false,
            false,
            false,
            true,
            false,
            true,
          ],
          livingArea: 58.45,
          summerArea: 6.94,
          fullArea: 65.39,
          entrance: 5.09,
          bathroom: 3.96,
          bedroom1: 14.53,
          bedroom2: 11.94,
          livingRoom: 21.22,
          images: [bina13_1, bina13_2]
        },
        {
          project: 14,
          name: "ტიპიური პროექტი 14",
          floors: [
            "I",
            "II",
            "III",
            "IV",
            "V",
            "VI",
            "VII",
            "VIII",
            "IX",
            "X",
            "XI",
          ],
          sold: [
            true,
            true,
            true,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            true,
          ],
          livingArea: 46.23,
          summerArea: 7.60,
          fullArea: 53.83,
          entrance: 4.94,
          bathroom: 3.74,
          bedroom1: 14.52,
          bedroom2: null,
          livingRoom: 21.59,
          images: [bina14_1, bina14_2]
        },
        {
          project: 15,
          name: "ტიპიური პროექტი 15",
          floors: [
            "I",
            "II",
            "III",
            "IV",
            "V",
            "VI",
            "VII",
            "VIII",
            "IX",
            "X",
            "XI",
          ],
          sold: [
            true,
            true,
            true,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            true,
          ],
          livingArea: 46.23,
          summerArea: 7.60,
          fullArea: 53.83,
          entrance: 4.94,
          bathroom: 3.9,
          bedroom1: 14.53,
          bedroom2: null,
          livingRoom: 21.21,
          images: [bina15_1, bina15_2]
        },
        {
          project: 16,
          name: "ტიპიური პროექტი 16",
          floors: [
            "I",
            "II",
            "III",
            "IV",
            "V",
            "VI",
            "VII",
            "VIII",
            "IX",
            "X",
            "XI",
          ],
          sold: [
            true,
            true,
            true,
            false,
            false,
            false,
            false,
            true,
            false,
            false,
            true,
          ],
          livingArea: 56.25,
          summerArea: 6.94,
          fullArea: 63.19,
          entrance: 5.28,
          bathroom: 3.74,
          bedroom1: 14.53,
          bedroom2: 9.79,
          livingRoom: 21.21,
          images: [bina16_1, bina16_2]
        },
      ]

}

export default MazaService;